services:
  - type: web
    name: rickandmorty
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn rick_and_morty_app.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: RENDER
        value: "1"
      - key: ALLOWED_HOSTS
        value: "rickandmorty-n0mo.onrender.com,.onrender.com,localhost,127.0.0.1"
      - key: RICK_AND_MORTY_API_BASE_URL
        value: "https://rickandmortyapi.com/api/"
