# Generated by Django 5.2.5 on 2025-08-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID из Rick and Morty API', unique=True)),
                ('name', models.CharField(help_text='Название эпизода', max_length=200)),
                ('air_date', models.CharField(blank=True, help_text='Дата выхода', max_length=100)),
                ('episode', models.CharField(blank=True, help_text='Номер эпизода (например, S01E01)', max_length=20)),
                ('url', models.URLField(blank=True, help_text='URL в API')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['episode'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID из Rick and Morty API', unique=True)),
                ('name', models.CharField(help_text='Название локации', max_length=200)),
                ('type', models.CharField(blank=True, help_text='Тип локации', max_length=100)),
                ('dimension', models.CharField(blank=True, help_text='Измерение', max_length=200)),
                ('url', models.URLField(blank=True, help_text='URL в API')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Поисковый запрос', max_length=500)),
                ('search_type', models.CharField(choices=[('character', 'Персонаж'), ('episode', 'Эпизод'), ('location', 'Локация')], help_text='Тип поиска', max_length=20)),
                ('results_count', models.IntegerField(default=0, help_text='Количество найденных результатов')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID из Rick and Morty API', unique=True)),
                ('name', models.CharField(help_text='Имя персонажа', max_length=200)),
                ('status', models.CharField(choices=[('alive', 'Живой'), ('dead', 'Мертвый'), ('unknown', 'Неизвестно')], default='unknown', help_text='Статус персонажа', max_length=20)),
                ('species', models.CharField(blank=True, help_text='Вид', max_length=100)),
                ('type', models.CharField(blank=True, help_text='Подтип/вариация', max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской'), ('genderless', 'Бесполый'), ('unknown', 'Неизвестно')], default='unknown', help_text='Пол персонажа', max_length=20)),
                ('image', models.URLField(blank=True, help_text='URL изображения персонажа')),
                ('url', models.URLField(blank=True, help_text='URL в API')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('episodes', models.ManyToManyField(blank=True, help_text='Эпизоды с участием персонажа', related_name='characters', to='main.episode')),
                ('location', models.ForeignKey(blank=True, help_text='Текущее местоположение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_characters', to='main.location')),
                ('origin', models.ForeignKey(blank=True, help_text='Место происхождения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_characters', to='main.location')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['name'],
            },
        ),
    ]
